### PR TITLE
Add basic scaling tests

### LINKED ISSUE #20: Auto-scaling e2e tests
## Description

Auto-scaling e2e tests are required to check for compliance and to test regression.

Each test case can be submitted in a separate PR starting with the simplest (1st) test-case.

## Test case: min scale

When using the `com.openfaas.scale.min` label, there should be a minimum number of replicas available via the API.

## Test case: scale from zero

1) Deploy function
2) Scale to zero
3) Wait until no ready replicas
4) Invoke function and make sure result is returned as 200

## Test case: auto-scaling up > min, then returning down to min

Test case may take up to 30s or 1m to complete, but can be run easily.

1) Deploy a function with min = 1, max = 2
2) Invoke function in a loop
3) Wait until replicas > min
4) Stop invoking function
5) Wait until function replicas returns to min

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Add tests scale for scaling up from zero when the function is invoked
- Add test case for setting the min replicas greater than 1
- Add test case for scaling up to a configured max replicas, waiting for
  the load to cooldown, and verifying that the function is scaled back
  down to the min (in this case 1)
- Move the function helpers to a separate file to make them easier to
  discover
- Add a scaleFunction helper
- Allow passing flags to the `go test` command, this is useful if you
  only want to run a single test; for example:

```
make -i test-kubernetes .TEST_FLAGS='-run ^Test_ScaleUpAndDownFromThroughPut$"'
```

- In the Makefile, create a separate list of test functions and pass
  that to the cleanup commands.  This also includes rewriting the clean
  target into a single command to kubectl. This makes it easier to add new
  functions and it should make the cleanup target easier to read.

Resolves #20

Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>

### CODE REVIEW

**Comment by LucasRoesler** [comment]
Derek set reviewer: alexellis

**Comment by alexellis** [comment]
There's a conflict on tests/deploy_test.go

**Comment by alexellis** [comment]
Thanks for this, could you close any pending PRs that are covered by this change?

**Comment by LucasRoesler** [comment]
This PR 

Resolves #13 
Closes #14 
Closes #21 
Closes #24

**Pull request merged**
