### PR TITLE
remove faas-swarm references

### PR DESCRIPTION
**Pull request by viveksyngh**
This commit removes faas-swarm references and support from this repo as faas-swarm has been
deprecated.

fixes: #76
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

### CODE REVIEW

**Comment by LucasRoesler** [comment]
@alexellis this PR is good, but the tests wont pass until after we merge #79

**Comment by alexellis** [comment]
@viveksyngh please could you rebase this? #79 is now merged.

**Comment by viveksyngh** [comment]
@alexellis Rebased it. Tests are passing now.

**Review by alexellis — APPROVED** [review]
Approved, already reviewed by @LucasRoesler

**Pull request merged**
