### PR TITLE
fix: wrong type in test

### PR DESCRIPTION
**Pull request by jonyhy96**
fix the reason of ci's [fail](https://travis-ci.com/github/openfaas/faas/builds/161571891)

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR, pinging @LucasRoesler

**Comment by alexellis** [comment]
@jonyhy96 it seems like the build is still failing, can you take another look at the errors?

**Comment by jonyhy96** [comment]
> @jonyhy96 it seems like the build is still failing, can you take another look at the errors?

OK,i will try to fix it.

**Comment by jonyhy96** [comment]
> @jonyhy96 it seems like the build is still failing, can you take another look at the errors?

I run the test locally and everything works well, If there is any place i can trigger re-run of the ci or debug into the failed job?
Looking forward for your help, Thanks!

**Comment by alexellis** [comment]
Yes click "details"

https://travis-ci.com/github/openfaas/certifier/builds/161600022

Screenshot 2020-04-23 at 12 36 52

**Comment by jonyhy96** [comment]
> Yes click "details"
> 
> https://travis-ci.com/github/openfaas/certifier/builds/161600022
> 
> Screenshot 2020-04-23 at 12 36 52

Yes, I already check this and it seems like i don't have the permission to re-run it or debug into the failed job. Can you re-run the failed job?

**Comment by alexellis** [comment]
To rerun push a commit. The logs are public and open to everyone.

**Comment by jonyhy96** [comment]
> To rerun push a commit. The logs are public and open to everyone.

The ci is passed now.By the way, Can you see the Restart build button on the failed job like the picture bellow?
image
Maybe we can trigger a re-run of the failed job without making a commit.

**Comment by alexellis** [comment]
Now, I wonder why faas-netes is also failing? https://travis-ci.com/openfaas/faas-netes

**Pull request merged**
