### PR TITLE
Use go modules

### LINKED ISSUE #30: Migrate to go modules
We could migrate from `dep` to Go modules like we are doing with many of the other projects, e.g. https://github.com/openfaas/faas-netes/issues/585

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Initialize the go.mod
- Remove the vendor
- Update to the latest faas-provider
- Remove the dependency on the gateway

Resolves #30

Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Lucas, #30 did not mention removing the vendor folder, was that the point of using go modules, or was it just to be more "up to date"?

**Comment by LucasRoesler** [comment]
I can add the vendor back, just need to update all the commands to force using the vendor as well

**Comment by LucasRoesler** [comment]
@alexellis updated the commit to readd the vendor

**Comment by alexellis** [comment]
Once merged, you will need to kick off a build in openfaas/faas by sending a PR to add whitespace or similar. Is that OK? Let me know when you're available so that this can be timed.

**Comment by LucasRoesler** [comment]
I should have time to do that today, around 10:30 CET

**Comment by alexellis** [comment]
@LucasRoesler the last I heard on this PR was that you were taking an action, how's that going?
 https://github.com/openfaas/certifier/pull/35#issuecomment-601191206

**Comment by alexellis** [comment]
I'm re-reading this as us needing to coordinate together, a Slack DM would have been better, I will invariably *not see* a GitHub comment.

**Comment by alexellis** [comment]
Merged, this will leave the build potentially broken until fixed. Please kick off a build in openfaas/faas and openfaas/faas-netes, you could just change some whitespace to achieve that.

**Comment by LucasRoesler** [comment]
openfaas/faas passed with the latest certifier https://github.com/openfaas/faas/pull/1499

**Pull request merged**
